"""MemoryCustodian CLI package."""

__version__ = "0.12.0"
__protocol_version__ = "0.8"
__entry_schema_version__ = "3"
__subject_schema_version__ = "1"
__routing_schema_version__ = "1"
__conflict_schema_version__ = "1"
__local_overlay_schema_version__ = "1"
__transaction_schema_version__ = "1"
__audit_schema_version__ = "1"
__output_schema_version__ = "1"
__erasure_scope_schema_version__ = "1"
